tty/amiserial: Add missing argument for tty_unlock()
commit c8034020103ec96fb6931059988a6f774dacaf02 ("tty_lock: Localise the lock")
missed that 83b1f4aa30a05a3fa9a1fd0e5f9a5b4517928fbf ("drivers/tty/amiserial.c:
add missing tty_unlock") just added a new caller of tty_unlock():

drivers/tty/amiserial.c: In function ‘set_serial_info’:
drivers/tty/amiserial.c:1077: error: too few arguments to function ‘tty_unlock’

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>