msm: ipa3: Use bitwise instead of logical operator
commit 2b3e460fd4c0 ("msm: ipa3: Fix IPA aggregation register val-mask
calculation") introduced a compile time error. The logical '&&' has been
used in a situation where the bitwise '&' operator is needed.

drivers/platform/msm/ipa/ipa_v3/ipahal/ipahal_reg.c:2132:67: error: use of logical '&&' with
      constant operand [-Werror,-Wconstant-logical-operand]
        valmask->val = (1 << IPA_ENDP_INIT_AGGR_n_AGGR_FORCE_CLOSE_SHFT) &&
                                                                         ^
drivers/platform/msm/ipa/ipa_v3/ipahal/ipahal_reg.c:2132:67: note: use '&' for a bitwise
      operation
        valmask->val = (1 << IPA_ENDP_INIT_AGGR_n_AGGR_FORCE_CLOSE_SHFT) &&
                                                                         ^~
                                                                         &
drivers/platform/msm/ipa/ipa_v3/ipahal/ipahal_reg.c:2132:67: note: remove constant to silence
      this warning
        valmask->val = (1 << IPA_ENDP_INIT_AGGR_n_AGGR_FORCE_CLOSE_SHFT) &&
                                                                        ~^~
drivers/platform/msm/ipa/ipa_v3/ipahal/ipahal_reg.c:2136:60: error: use of logical '&&' with
      constant operand [-Werror,-Wconstant-logical-operand]
        valmask->val |= ((0 << IPA_ENDP_INIT_AGGR_n_AGGR_EN_SHFT) &&
                                                                  ^
drivers/platform/msm/ipa/ipa_v3/ipahal/ipahal_reg.c:2136:60: note: use '&' for a bitwise
      operation
        valmask->val |= ((0 << IPA_ENDP_INIT_AGGR_n_AGGR_EN_SHFT) &&
                                                                  ^~
                                                                  &
drivers/platform/msm/ipa/ipa_v3/ipahal/ipahal_reg.c:2136:60: note: remove constant to silence
      this warning
        valmask->val |= ((0 << IPA_ENDP_INIT_AGGR_n_AGGR_EN_SHFT) &&
                                                                 ~^~
2 errors generated.

Fixes: 2b3e460fd4c0 ("msm: ipa3: Fix IPA aggregation register val-mask calculation")
Signed-off-by: Daniel Mentz <danielmentz@google.com>
Change-Id: Ia077e270743e4551e4b7777c2ced5b021487fff6
CRs-fixed: 2196859
Signed-off-by: Ghanim Fodi <gfodi@codeaurora.org>