Revert "usb: host/sl811-hcd: fix sparse warning"
This reverts commit f35b875c3859e6cbe7027b3434a791fa243bcb59.

Commit f35b875c3859 results in the following error when compiling
x86_64:allyesconfig.

sl811_cs.c:(.text+0x1d3cb72): undefined reference to `sl811h_driver'

Fixes: f35b875c3859 ("usb: host/sl811-hcd: fix sparse warning")
Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>