include/video/atmel_lcdc.h must #include <linux/workqueue.h>
This patch fixes the following compile error caused by commit
bc59210dce0ed2ffd55d6c1bebc69ebf0b4e0fda ("atmel_lcdfb: FIFO underflow
management"):

  In file included from arch/avr32/boards/atstk1000/atstk1004.c:21:
  include/video/atmel_lcdc.h:40: error: field 'task' has incomplete type

Signed-off-by: Adrian Bunk <bunk@kernel.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>