usb: phy: fix dual role sysfs build if kernel modules are supported
Add a missing ";" after EXPORT_SYMBOL() otherwise we run
into following build error if Kernel Modules are supported:
----------
  CC      drivers/usb/phy/class-dual-role.o
drivers/usb/phy/class-dual-role.c:91:1: error: expected ',' or ';' before 'int'
 int dual_role_get_property(struct dual_role_phy_instance *dual_role,
 ^
make[3]: *** [drivers/usb/phy/class-dual-role.o] Error 1
----------

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>
(cherry picked from commit 78aa09acc867ddaa4fa7a369426678780568a917)

Git-commit: 78aa09acc867ddaa4fa7a369426678780568a917
Git-repo: https://android.googlesource.com/kernel/common/
Change-Id: I7ec77584b3a753448ddc50a74204a20f4636f8a4
Signed-off-by: Manu Gautam <mgautam@codeaurora.org>