Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
This reverts commit 51faa0a451ed259b895fce134f0d4da2727f7e73, which
causes a build failure:

drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer