Fix imx cpufreq driver as module
When building as module:
ERROR: "cpufreq_gov_performance" [arch/arm/plat-mxc/cpufreq.ko] undefined!
WARNING: modpost: Found 1 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
make[1]: *** [__modpost] Error 1
make: *** [modules] Error 2

It's due to the driver using CPUFREQ_DEFAULT_GOVERNOR, even it should not
(see commit a9d52c53f7ff1f4dc2b6b12e4045ae58c3ba1492 in Linus tree), so
remove it.

Signed-off-by: Arnaud Patard <arnaud.patard@rtp-net.org>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>