ANDROID: dm verity: Export dm_disk
Commit 487341b ("ANDROID: dm verity: port upstream changes to 3.18")
missed out on exporting dm_disk() while backporting upstream changes
to android-3.18. That resulted in following error when building
dm-verity driver as a module:

ERROR: "dm_disk" [drivers/md/dm-verity.ko] undefined!

Fixes: Change-Id: I0ddadfcc4104b9d38554003203f6e65191ffe995
       ("ANDROID: dm verity: port upstream changes to 3.18")
Change-Id: Id0e0f1e52efa2764faefdc5ae8bd76c7d608ef93
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>