arm64: move mixed endian EL0 declarations under __ASSEMBLY__ guards
Move "mixed endian EL0" declarations from AOSP commit db039697c,
"arm64: Track system support for mixed endian EL0", under
__ASSEMBLY__ guards otherwise we run into following build error:

----------
./arch/arm64/include/asm/cpufeature.h: Assembler messages:
./arch/arm64/include/asm/cpufeature.h:58: Error: unknown mnemonic `bool' -- `bool cpu_supports_mixed_endian_el0(void)'
./arch/arm64/include/asm/cpufeature.h:59: Error: unknown mnemonic `bool' -- `bool system_supports_mixed_endian_el0(void)'
make[1]: *** [arch/arm64/kernel/entry.o] Error 1
make: *** [arch/arm64/kernel] Error 2
----------

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>