Revert "[media] siano: apply debug flag to module level"
This reverts commit 5e13ec4b86b0a04cdf6ff24b7f00a5c862e92357.

As reported by Stephen Rothwell:

After merging the v4l-dvb tree, today's linux-next build (x86_64
allmodconfig) failed like this:

ERROR: "sms_dbg" [drivers/media/dvb/siano/smsusb.ko] undefined!
ERROR: "sms_dbg" [drivers/media/dvb/siano/smsdvb.ko] undefined!

Caused by commit 5e13ec4b86b0 ("[media] siano: apply debug flag to module
level").

Relevant config:
CONFIG_SMS_SIANO_MDTV=m
CONFIG_SMS_USB_DRV=m
CONFIG_SMS_SDIO_DRV=m

Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>