blackfin: twi: Remove bogus #endif
arch/blackfin/mach-bf538/boards/ezkit.c:768:2: error: #endif without #if

Introduced by commit 416428b4ea938d1a1198fe270e893846e003151d ("blackfin:
twi: Move TWI peripheral pin request array to platform data"), which
removed the #if, but forgot about the #endif.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Signed-off-by: Steven Miao <realmz6@gmail.com>