tracing, net: fix net tree and tracing tree merge interaction
Today's linux-next build (powerpc ppc64_defconfig) failed like this:

 In file included from net/core/skbuff.c:69:
 include/trace/skb.h:4: error: expected ')' before '(' token
 include/trace/skb.h:4: error: expected ')' before '(' token
 [...]

Caused by commit 6a03ec4568adf6c8a8ab9a7e421b2d33093bd892 ("tracing:
replace TP<var> with TP_<var>") from the tracing tree interacting with
commit 2fb3a50ba006913b41f547ddbbc0b8cb9a96fcec ("Network Drop Monitor:
Add trace declaration for skb frees") from the net tree.

Acked-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Ingo Molnar <mingo@elte.hu>